### ISSUE TITLE
debug flag causes unhandled exception 

### ISSUE THREAD

**Issue by Timothy-G-Griffin** [rabeckett/propane#2]
The virtualbox image at http://www.cs.princeton.edu/~rbeckett/Propane/Installation.html
seems to throw and exception when the --debug flag is used

**Comment by rabeckett** [comment]
Thanks for pointing this out. It seems that the graphviz "dot" utility does not like newlines in strings on Linux only. I pushed a fix and updated the virtualbox image.

**Comment by Timothy-G-Griffin** [comment]
Wonderful.  Thanks.
