### ISSUE TITLE
Community addition syntax

### ISSUE THREAD

**Issue by ratulm** [rabeckett/propane#4]
The current Propane code generates lines like these:

!
route-map rm-in permit 10
  .... 
  set community additive 100:1 
!

Per http://www.nongnu.org/quagga/docs/docs-multi/BGP-Community-in-Route-Map.html, the 'additive' keyword should be after the community. I believe that is how Cisco is too. 

Can we change the order?

**Comment by rabeckett** [comment]
Just pushed a fix changing the order.

It's weird that it worked fine in the emulator with the bad syntax. I wonder if it was ignoring the additive keyword, which would work correctly in most but not all cases.

**Comment by ratulm** [comment]
cool, thanks. with this change and some others i made to batfish, propane configs parse out of the box. confederations are not modeled but we can get to that.
